SIGN_IN_BUTTON_PATH = '//*[@id=":rb:"]/span'
EMAIL_XPATH = '//*[@id="email"]'
LOGIN_NEXT_STEP_BTN_XPATH='//*[@id="new_user"]/font/font/input'
PASSWORD_XPATH = '//*[@id="password"]'
NEXT_STEP_XPATH = '//*[@id="new_user"]/input[2]'
USER_FUNC_MODEL_PANEL_XPATH = '/html/body/div[6]/div[2]'
USER_FUNC_MODEL_OTHER_BTN_XPATH = '/html/body/div[6]/div[2]/div[2]/div[2]/button[8]'
USER_FUNC_MODEL_CONFIRM_BTN_XPATH = '/html/body/div[6]/div[2]/div[3]/button'
TOP_CHARTS_XPATH = '/html/body/div[3]/div/div[2]/ul[3]/li[1]/span'
TOP_CHARTS_SELECTER_XPATH = '/html/body/div[3]/div/div[2]/ul[3]/li[3]/div/ul[1]/li[1]'
GAMES_CATEGORY_XPATH = '//*[@id="mainContent"]/div[1]/div/div[2]/div/div[4]/div'
GAMES_CATEGORY_SELECTED_XPATH = '//*[@id="menu-"]/div[3]/ul/li[9]'
ALLGAMES_CATEGORY_SELECTED_XPATH = '//*[@id="menu-"]/div[3]/ul/li[10]'
